import http from "http"; import fs from "fs"; import path from "path";
import { chromium } from "playwright";
const ROOT=path.resolve("public"), SHOTS=path.resolve("test/shots");
const T={".html":"text/html",".css":"text/css",".js":"text/javascript",".png":"image/png",".webmanifest":"application/manifest+json"};
const srv=http.createServer((q,r)=>{let p=path.join(ROOT,decodeURIComponent(q.url.split("?")[0])); if(q.url==="/")p=path.join(ROOT,"index.html"); if(q.url.includes("/.netlify/")){r.writeHead(404);r.end();return;} fs.readFile(p,(e,d)=>{if(e){r.writeHead(404);r.end();return;} r.writeHead(200,{"Content-Type":T[path.extname(p)]||"application/octet-stream"});r.end(d);});});
await new Promise(r=>srv.listen(8245,r));
const b=await chromium.launch();
const page=await (await b.newContext({viewport:{width:414,height:900}})).newPage();
await page.goto("http://localhost:8245/index.html",{waitUntil:"domcontentloaded"});
await page.waitForSelector("#app:not([hidden])");
await page.fill("#login-name","Gabi"); await page.click('button:has-text("C\'est parti")');
await page.waitForSelector(".map-viewport");
await page.evaluate(()=>{ const s=CV.Store.current(); s.fiches={"mod-fr-natures":true}; CV.Store.save(); });
await page.click('.nav-btn[data-go="#/recompenses"]');
await page.waitForSelector(".fiche-grid");
await page.locator(".fiche-cell:not(.locked)").first().scrollIntoViewIfNeeded();
await page.locator(".fiche-cell:not(.locked)").first().click();
await page.waitForSelector(".fiche-sheet");
await page.waitForTimeout(200);
const geo = await page.evaluate(()=>{ const s=document.querySelector(".fiche-sheet"); const r=s.getBoundingClientRect();
  return { top:Math.round(r.top), visible:r.top>0 && r.top<600, z:getComputedStyle(s).zIndex, h:Math.round(r.height) }; });
console.log("Modale fiche :", geo);
await page.screenshot({path:path.join(SHOTS,"fiche-modal.png")});
await b.close(); srv.close();
