import { chromium } from "playwright";
const errors=[], missing=[];
const b=await chromium.launch();
const page=await (await b.newContext({viewport:{width:414,height:900}})).newPage();
page.on("pageerror",e=>errors.push("PAGEERROR: "+e.message));
page.on("console",m=>{ if(m.type()==="error") errors.push(m.text().slice(0,80)); });
page.on("response",r=>{ if(r.status()>=400) missing.push(r.status()+" "+r.url().split("/").pop()); });
await page.goto("https://ghosteden.github.io/cahier-aventure/",{waitUntil:"domcontentloaded"});
await page.waitForSelector("#app:not([hidden])",{timeout:15000});
await page.waitForTimeout(1500);
// démarre une partie pour vérifier que tout se charge
await page.fill("#login-name","Test");
await page.click('button:has-text("C\'est parti")');
await page.waitForSelector(".map-viewport",{timeout:10000});
const world = await page.evaluate(()=>CV.WORLDS.length+" mondes, "+CV.buildProgram().length+" niveaux");
const title = await page.title();
console.log("Titre page :", title);
console.log("Contenu chargé :", world);
console.log("Ressources en erreur (4xx/5xx) :", missing.length? missing.slice(0,5).join(", "):"aucune ✅");
console.log("Erreurs JS :", errors.length? errors.slice(0,4):"aucune ✅");
await page.screenshot({path:"test/shots/live-carte.png"});
await b.close();
