import http from "http"; import fs from "fs"; import path from "path";
import { chromium } from "playwright";
const ROOT=path.resolve("public"), SHOTS=path.resolve("test/shots");
const T={".html":"text/html",".css":"text/css",".js":"text/javascript",".png":"image/png",".webmanifest":"application/manifest+json"};
const srv=http.createServer((q,r)=>{let p=path.join(ROOT,decodeURIComponent(q.url.split("?")[0])); if(q.url==="/")p=path.join(ROOT,"index.html"); if(q.url.includes("/.netlify/")){r.writeHead(404);r.end();return;} fs.readFile(p,(e,d)=>{if(e){r.writeHead(404);r.end();return;} r.writeHead(200,{"Content-Type":T[path.extname(p)]||"application/octet-stream"});r.end(d);});});
await new Promise(r=>srv.listen(8243,r));
const errors=[]; const b=await chromium.launch();
const page=await (await b.newContext({viewport:{width:414,height:900}})).newPage();
page.on("pageerror",e=>errors.push("PAGEERROR: "+e.message));
await page.goto("http://localhost:8243/index.html",{waitUntil:"domcontentloaded"});
await page.waitForSelector("#app:not([hidden])");
await page.fill("#login-name","Gabi"); await page.click('button:has-text("C\'est parti")');
await page.waitForSelector(".map-viewport");
await page.evaluate(()=>{const s=CV.Store.current(); s.currentDay=45; s.heroWorld=4;
  s.dayProgress=s.dayProgress||{}; const wi=CV.freeWorldIndex(); for(let i=0;i<8;i++) s.dayProgress[CV.levelNumber(wi,i)]={done:true,stars:3};
  CV.Store.save();});
await page.reload({waitUntil:"domcontentloaded"});
await page.waitForSelector(".map-viewport"); await page.waitForTimeout(500);
await page.evaluate(()=>{ CV.PLANETS[8].duration = 30; });
await page.evaluate(()=>document.querySelectorAll(".planet-hit")[8].click());
await page.waitForSelector(".node-sheet");
await page.locator('.node-sheet .btn.big').click();
await page.waitForSelector(".reward-stage",{timeout:5000});
const y = async ()=> page.evaluate(()=>parseFloat(document.querySelector(".reward-ship").style.top));
// 1) sans rien faire : la fusée doit TOMBER (y augmente)
await page.waitForTimeout(700);
const yFall = await y();
// 2) en maintenant appuyé : elle doit REMONTER (y diminue)
const box = await page.locator(".reward-stage").boundingBox();
await page.mouse.move(box.x+box.width/2, box.y+box.height/2);
await page.mouse.down();
await page.waitForTimeout(900);
const yThrust = await y();
await page.mouse.up();
console.log("Chute libre  → top =", yFall.toFixed(1), "% (doit descendre, >50)");
console.log("Appui tenu   → top =", yThrust.toFixed(1), "% (doit être remonté, <", yFall.toFixed(1)+")");
console.log(yFall>52 && yThrust<yFall ? "✅ pilotage type Flappy OK" : "❌ physique incorrecte");
await page.screenshot({path:path.join(SHOTS,"pluton-fly.png")});
console.log("Erreurs JS:", errors.length, errors.slice(0,3));
await b.close(); srv.close();
