import http from "http"; import fs from "fs"; import path from "path";
import { chromium } from "playwright";
const ROOT=path.resolve("public");
const T={".html":"text/html",".css":"text/css",".js":"text/javascript",".png":"image/png",".webmanifest":"application/manifest+json"};
const srv=http.createServer((q,r)=>{let p=path.join(ROOT,decodeURIComponent(q.url.split("?")[0])); if(q.url==="/")p=path.join(ROOT,"index.html"); if(q.url.includes("/.netlify/")){r.writeHead(404);r.end();return;} fs.readFile(p,(e,d)=>{if(e){r.writeHead(404);r.end();return;} r.writeHead(200,{"Content-Type":T[path.extname(p)]||"application/octet-stream"});r.end(d);});});
await new Promise(r=>srv.listen(8222,r));
const b=await chromium.launch();
const page=await (await b.newContext({viewport:{width:414,height:900}})).newPage();
const reqs=[]; let t0=0;
page.on("request",r=>{ const u=r.url(); if(/hero-espace-/.test(u)) reqs.push([u.split("/").pop(), t0?Date.now()-t0:null]); });
await page.goto("http://localhost:8222/index.html",{waitUntil:"domcontentloaded"});
await page.waitForSelector("#app:not([hidden])");
await page.fill("#login-name","Gabi"); await page.click('button:has-text("C\'est parti")');
await page.waitForSelector(".map-viewport");
await page.evaluate(()=>{const s=CV.Store.current(); s.currentDay=39; CV.Store.save(); location.reload();});
await page.waitForSelector(".map-viewport");
await page.evaluate(()=>{ CV.drawMix=()=>Array.from({length:8},()=>({type:"qcm",q:"2+2 ?",choices:["4","5","6"],answer:0})); });
await page.waitForTimeout(400);
await page.locator(".stone.current").click({force:true});
await page.waitForSelector(".node-sheet");
await page.click('.node-sheet button:has-text("Jouer"), .node-sheet button:has-text("Rejouer")');
await page.waitForSelector(".planet-stage");
t0=Date.now();
console.log("Planches demandées à l'ouverture de la scène :");
await page.waitForTimeout(600);
reqs.forEach(([f])=>console.log("   -", f));
// on avance jusqu'au segment de MARCHE (3e bonne réponse) et on vérifie qu'aucune image n'est redemandée
reqs.length=0;
for(let i=0;i<3;i++){ await page.locator(".choice").first().click(); await page.waitForTimeout(1300); }
console.log("Images redemandées pendant la marche :", reqs.length ? reqs.map(r=>r[0]) : "aucune ✅ (tout était déjà en mémoire)");
await b.close(); srv.close();
